plugin-prefix: "#00ddfb&lC#56eafa&ll#abf7f9&lo#b9f1f3&lu#80dae8&ld#46c3de&ly &8&l≫ &r"
shop-search-loading-message: "&7Searching..."
shop-sorting-method: 2
shop-gui-item-lore:
  - ""
  - "&fPrice: &a${ITEM_PRICE}"
  - "&fStock: &7{SHOP_STOCK}"
  - "&fOwner: &7{SHOP_OWNER}"
  - "&fLocation: &7{SHOP_LOC}"
  - "&fShop Visits: &7{SHOP_VISITS}"
  - ""
player-shop-teleportation:
  direct-shop-tp-mode:
    tp-player-directly-to-shop: true
    click-to-teleport-message: "&6&lClick to teleport to the shop!"
    shop-tp-no-permission-message: "&cYou don't have permission to teleport to this shop!"
    unsafe-shop-area-message: "&cThe area around this shop is unsafe!"
    tp-delay-in-seconds: 0
    tp-delay-message: "&6You will be teleported in &c{DELAY} &6seconds..."
    tp-to-own-shop-no-permission-message: "&cYou cannot teleport to your own shop!"
shop-gui-back-button-material: ""
shop-gui-back-button-text: "&7&l« &cPrev Page"
shop-gui-next-button-material: ""
shop-gui-next-button-text: "&aNext Page &7&l»"
shop-gui-filler-item: "GRAY_STAINED_GLASS_PANE"
shop-gui-close-button-material: "BARRIER"
shop-gui-close-button-text: "&fClose Search"
shop-gui-goto-first-page-button-material: ""
shop-gui-goto-first-page-button-text: "&7&l« &cGo to First Page"
shop-gui-goto-last-page-button-material: ""
shop-gui-goto-last-page-button-text: "&aGo to Last Page &7&l»"
shop-gui-back-button-custom-model-data: ""
shop-gui-next-button-custom-model-data: ""
shop-gui-goto-first-page-button-custom-model-data: ""
shop-gui-goto-last-page-button-custom-model-data: ""
shop-gui-close-button-custom-model-data: ""
shop-navigation-first-page-alert-message: "&cYou are already on the first page!"
shop-navigation-last-page-alert-message: "&cYou are already on the last page!"
shop-player-visit-cooldown-in-minutes: 5
ignore-empty-chests: true
blacklisted-worlds:
  - "world_number_1"
  - "world_number_2"
debug-mode: false
config-version: 14